// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpwmosaxjdeqaazzejwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wd21vc2F4amRlcWFhenplandlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjk4MjUsImV4cCI6MjA1ODcwNTgyNX0.9XlqOugCYE1z0ciC6qmh_GFNmdYfYnLBBhIQIlu0Ax0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);